<?php

namespace app\models;

use Yii;


class Afish extends \yii\db\ActiveRecord
{
    const STATUS_ALLOW = 1;
    const STATUS_DISALLOW = 0;
    /**
     * @var mixed|\yii\web\UploadedFile|null
     */

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    /**
     * @var int|mixed|string|null
     */

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'afish';
    }


    public function rules()
    {
        return [
            /*
            [['description', 'content'], 'string'],
            [['viewed', 'catalog_id'], 'integer'],
            [['name', 'image'], 'string', 'max' => 255],
*/
            [['catalog_id'], 'integer'],
            [['name'], 'required'],
            [['name','description','content'],'string'],
            ['date', 'datetime', 'format' => 'php:Y-m-d H:i:s'],
            [['date'], 'default', 'value' => date('Y-m-d')],
            [['name','phone'],'string','max'=> 255],
            [['image'], 'file', 'extensions' => 'png, jpg'],
            ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя/Название услуги',
            'description' => 'Краткое описание',
            'phone' => 'Номер телефона',
            'content' => 'Основной контент',
            'image' => 'Изображение',
            'viewed' => 'Просмотры',
            'catalog_id' => 'Категория услуги',
        ];
    }

    public function saveArticle()
    {
        $this->user_id = Yii::$app->user->id;
        return $this->save(false);
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->image) ? '/web/uploads/afish/' . $this->image : '/web/no-image.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getCatalog()
    {
        return $this->hasOne(Catalog::className(),['id'=>'catalog_id']);
    }

    public function saveCatalog($catalog_id)
    {
        $catalog = Catalog::findOne($catalog_id);
        if($catalog != null)
        {
            $this->link('catalog',$catalog);
            return true;
        }

    }

    public function viewedCounter()
    {
        $this->viewed += 1;
        return $this->save(false);
    }

    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id'=>'user_id']);
    }

    public function getComments()
    {
        return $this->hasMany(Comment::className(),['afish_id'=>'id']);
    }

    public function getAfishComments()
    {
        return $this->getComments()->where(['status'=>1])->all();
    }

    public function getCountComments()
    {
        return $this->getComments()->where(['status'=>1])->count();
    }

    public function getPopular()
    {
        return Afish::find()->orderBy('viewed desc')->limit(3)->all();
    }
    public function getDate()
    {
        return Yii::$app->formatter->asDate($this->date);
    }

    public function getRecent()
    {
        return Afish::find()->orderBy('date asc')->limit(3)->all();
    }

    public function upload() {
        if ($this->validate()){
            $path = 'uploads/afish/' . $this->image->baseName . '.'  . $this->image->extension;
            $this->image->saveAs($path);
            //@unlink($path);
            return true;
        }else{
            //$errors = $this->getErrors();
            //var_dump($errors);
            return false;
        }
    }

    public function deleteCover() {
        if ($this->image){
            $path = 'uploads/afish/' . $this->image;
            @unlink($path);
            return true;
        }else{
            return false;
        }
    }

    public function isAllowed()
    {
        return $this->status;
    }

    public function allow()
    {
        $this->status = self::STATUS_ALLOW;
        return $this->save(false);
    }

    public function disallow()
    {
        $this->status = self::STATUS_DISALLOW;
        return $this->save(false);
    }

}
